### ISSUE TITLE
int menu()

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/Trucos_con_cartas#2]
Opciones: Cargar, barajar, añadir, cortar, guardar, salir

**Comment by Jsevillamol** [comment]
Para la parte opcional quiero un menú de menús, que incluya:
-Opciones de cargado y guardado
-Opciones de manipulación de mazos
-Juegos de cartas
-Juegos de magia

**Comment by vigonz06** [comment]
En opciones de cargado, a parte de cargar mazo y guardar, que mas habría?

**Comment by Jsevillamol** [comment]
Agregar

**Comment by Jsevillamol** [comment]
@vigonz06 Faltan los prototipos de los menús.

**Comment by vigonz06** [comment]
prototipos añadidos

**Comment by Jsevillamol** [comment]
Al salir de un submenú, sale el menú principal. Cuando seleccionas opción, aparece de nuevo el menú principal.
Solución: quitar las llamadas a función después de cada submenú y usar una variable distinta en cada nivel de profundidad para seleccionar (int opcion para el principal, int seleccionar para el resto).
