### ISSUE TITLE
void trucoPosada()

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/Trucos_con_cartas#22]

**Comment by vigonz06** [comment]
Varias cosas:
El fix en desplazar() a donde lo has subido, máster o truco_posada?
Con eso se supone que unir() debería funcionar?
Si es así, cierro esta issue?

**Comment by Jsevillamol** [comment]
@vigonz06 EL fix está en master. Haz un merge y testea truco_posada antes de cerrar la issue.

**Comment by vigonz06** [comment]
Esta funciona
