### ISSUE TITLE
¿Que tal añadir juegos de cartas?

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/Trucos_con_cartas#35]
Ya que tenemos un soporte para editar mazos, podemos programar distintos juegos de cartas.

Algunas ideas:
-Blackjack
-Poker Texas Hold'em
-Canasta

**Comment by vigonz06** [comment]
La idea es buena, lo único, la práctica no era exclusiva de cartomagia?

**Comment by Jsevillamol** [comment]
Ya en la parte opcional no pienso contenerme.
¡Demos rienda suelta a la creatividad!

**Comment by Jsevillamol** [comment]
Se nos va de las manos la cosa. Terminamos BJ y finito.
