### ISSUE TITLE
Cartas de la nada

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/Trucos_con_cartas#44]
En los tres trucos de magia se muestra bien el mazo la primera vez, pero una vez que se lo traga la consola, cuando vuelve a escupirlo salen cartas de mas

**Comment by Jsevillamol** [comment]
@vigonz06 creo que el fix a unir() ya debería haberlo arreglado. Testea de nuevo.

**Comment by vigonz06** [comment]
ya no pasa
