### ISSUE TITLE
Repartir_n_cartas()

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/Trucos_con_cartas#48]
Permite repartir un numero determinado de cartas a un jugador concreto

**Comment by Jsevillamol** [comment]
Creo que voy a incorporar un puntero de lectura a la struct tMazo. De esa manera, podemos ir repartiendo cartas sin repetir las que salen y el mazo se va quedando "vacío" sin necesidad de vaciarlo realmente.

**Comment by Jsevillamol** [comment]
Done.
