### ISSUE TITLE
Opciones_de_jugador()

### ISSUE THREAD

**Issue by vigonz06** [Jsevillamol/Trucos_con_cartas#49]
Menú que se le muestra al jugador para que decida que hacer: pedir, plantarse, doblar apuesta, dividir o abandonar.
Ya tengo un proyecto de esta hecho
Si me dejo alguna opción dímelo y la meto
Cada opción se controlaría con una funcion

**Comment by Jsevillamol** [comment]
Está bien.
Por el momento no te preocupes por la opción de dividir, que es (medianamente) complicada de implementar. Luego si eso ya la ponemos.
