### ISSUE TITLE
No me entero de que pasa

### ISSUE THREAD

**Issue by Jsevillamol** [Jsevillamol/Trucos_con_cartas#56]
Quiero más información disponible durante la ejecución de BJ.
Me refiero a las cartas que me reparten, etc.

**Comment by Jsevillamol** [comment]
@vigonz06, cuando puedas, añade más detalles, como la causa de que pierdas o ganes, que se muestren ambas manos al final, etc.

**Comment by vigonz06** [comment]
if what I've done until now is not enought, sorry, but time has come to the end
